# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chiSqTestTbl <- function(ctg, correct = TRUE, crash = TRUE) {
    .Call('_fastTest_chiSqTestTbl', PACKAGE = 'fastTest', ctg, correct, crash)
}

chiSqTestVec <- function(x, f, correct = TRUE, crash = TRUE) {
    .Call('_fastTest_chiSqTestVec', PACKAGE = 'fastTest', x, f, correct, crash)
}

chiSqTestMtx <- function(x, f, correct = TRUE, crash = TRUE) {
    .Call('_fastTest_chiSqTestMtx', PACKAGE = 'fastTest', x, f, correct, crash)
}

Table <- function(x) {
    .Call('_fastTest_Table', PACKAGE = 'fastTest', x)
}

xTable <- function(x, f) {
    .Call('_fastTest_xTable', PACKAGE = 'fastTest', x, f)
}

irrTable <- function(x, y) {
    .Call('_fastTest_irrTable', PACKAGE = 'fastTest', x, y)
}

permCorVec <- function(x, y, method = "pearson", alternative = "two.sided", n_iter = 1000L) {
    .Call('_fastTest_permCorVec', PACKAGE = 'fastTest', x, y, method, alternative, n_iter)
}

permCorMtx <- function(x, method = "pearson", alternative = "two.sided", n_iter = 1000L) {
    .Call('_fastTest_permCorMtx', PACKAGE = 'fastTest', x, method, alternative, n_iter)
}

bootCorVec <- function(x, y, method = "pearson", ci_type = "bca", conf_level = 0.95, n_iter = 1000L) {
    .Call('_fastTest_bootCorVec', PACKAGE = 'fastTest', x, y, method, ci_type, conf_level, n_iter)
}

bootCorMtx <- function(x, method = "pearson", ci_type = "bca", conf_level = 0.95, n_iter = 1000L) {
    .Call('_fastTest_bootCorMtx', PACKAGE = 'fastTest', x, method, ci_type, conf_level, n_iter)
}

Cov <- function(x, y, method = "pearson") {
    .Call('_fastTest_Cov', PACKAGE = 'fastTest', x, y, method)
}

CovMtx <- function(x, method = "pearson") {
    .Call('_fastTest_CovMtx', PACKAGE = 'fastTest', x, method)
}

Cor <- function(x, y, method = "pearson") {
    .Call('_fastTest_Cor', PACKAGE = 'fastTest', x, y, method)
}

CorMtx <- function(x, method = "pearson") {
    .Call('_fastTest_CorMtx', PACKAGE = 'fastTest', x, method)
}

setFisher <- function(x, all, dict, laplace = 1.0) {
    .Call('_fastTest_setFisher', PACKAGE = 'fastTest', x, all, dict, laplace)
}

setEnrichment <- function(x, all, dict, ci_type = "bca", conf_level = 0.95, n_iter = 100L, laplace = 1.0) {
    .Call('_fastTest_setEnrichment', PACKAGE = 'fastTest', x, all, dict, ci_type, conf_level, n_iter, laplace)
}

friedmanVec <- function(x, f, b, crash = FALSE) {
    .Call('_fastTest_friedmanVec', PACKAGE = 'fastTest', x, f, b, crash)
}

friedmanMtx <- function(x, f, b, crash = FALSE) {
    .Call('_fastTest_friedmanMtx', PACKAGE = 'fastTest', x, f, b, crash)
}

kappaCpp <- function(x, y, type) {
    .Call('_fastTest_kappaCpp', PACKAGE = 'fastTest', x, y, type)
}

kappaMtx <- function(x, y, type) {
    .Call('_fastTest_kappaMtx', PACKAGE = 'fastTest', x, y, type)
}

kruskalVec <- function(x, f, crash = TRUE) {
    .Call('_fastTest_kruskalVec', PACKAGE = 'fastTest', x, f, crash)
}

kruskalMtx <- function(x, f, crash = TRUE) {
    .Call('_fastTest_kruskalMtx', PACKAGE = 'fastTest', x, f, crash)
}

leveneBase <- function(x, type = "standard") {
    .Call('_fastTest_leveneBase', PACKAGE = 'fastTest', x, type)
}

leveneVec <- function(x, f, type = "standard", crash = TRUE) {
    .Call('_fastTest_leveneVec', PACKAGE = 'fastTest', x, f, type, crash)
}

leveneMtx <- function(x, f, type = "standard", crash = TRUE) {
    .Call('_fastTest_leveneMtx', PACKAGE = 'fastTest', x, f, type, crash)
}

mtxProduct <- function(x, y) {
    .Call('_fastTest_mtxProduct', PACKAGE = 'fastTest', x, y)
}

metaVec <- function(y, e, type = "fixed", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_metaVec', PACKAGE = 'fastTest', y, e, type, alternative, conf_level, crash)
}

metaMtx <- function(y, e, type = "fixed", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_metaMtx', PACKAGE = 'fastTest', y, e, type, alternative, conf_level, crash)
}

metaList <- function(y, e, type = "fixed", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_metaList', PACKAGE = 'fastTest', y, e, type, alternative, conf_level, crash)
}

Median <- function(x, na_rm = TRUE) {
    .Call('_fastTest_Median', PACKAGE = 'fastTest', x, na_rm)
}

Var <- function(x, na_rm = TRUE) {
    .Call('_fastTest_Var', PACKAGE = 'fastTest', x, na_rm)
}

SD <- function(x, na_rm = TRUE) {
    .Call('_fastTest_SD', PACKAGE = 'fastTest', x, na_rm)
}

SEM <- function(x, na_rm = TRUE) {
    .Call('_fastTest_SEM', PACKAGE = 'fastTest', x, na_rm)
}

locationStd <- function(x, y) {
    .Call('_fastTest_locationStd', PACKAGE = 'fastTest', x, y)
}

locationPair <- function(x) {
    .Call('_fastTest_locationPair', PACKAGE = 'fastTest', x)
}

Quantile <- function(x, probs) {
    .Call('_fastTest_Quantile', PACKAGE = 'fastTest', x, probs)
}

perCI <- function(theta, conf_level = 0.95) {
    .Call('_fastTest_perCI', PACKAGE = 'fastTest', theta, conf_level)
}

BCA <- function(theta, conf_level = 0.95) {
    .Call('_fastTest_BCA', PACKAGE = 'fastTest', theta, conf_level)
}

oneAnovaBase <- function(x) {
    .Call('_fastTest_oneAnovaBase', PACKAGE = 'fastTest', x)
}

oneAnovaVec <- function(x, f, crash = FALSE) {
    .Call('_fastTest_oneAnovaVec', PACKAGE = 'fastTest', x, f, crash)
}

oneAnovaMtx <- function(x, f, crash = TRUE) {
    .Call('_fastTest_oneAnovaMtx', PACKAGE = 'fastTest', x, f, crash)
}

oneBlockAnovaVec <- function(x, f, b) {
    .Call('_fastTest_oneBlockAnovaVec', PACKAGE = 'fastTest', x, f, b)
}

oneBlockAnovaMtx <- function(x, f, b, crash = TRUE) {
    .Call('_fastTest_oneBlockAnovaMtx', PACKAGE = 'fastTest', x, f, b, crash)
}

rankBlockVectors <- function(x, f, b) {
    .Call('_fastTest_rankBlockVectors', PACKAGE = 'fastTest', x, f, b)
}

setCtg <- function(x, all, entry) {
    .Call('_fastTest_setCtg', PACKAGE = 'fastTest', x, all, entry)
}

tTestStd <- function(x, y, type = "standard", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_tTestStd', PACKAGE = 'fastTest', x, y, type, alternative, conf_level, crash)
}

tTestVec <- function(x, f, type = "standard", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_tTestVec', PACKAGE = 'fastTest', x, f, type, alternative, conf_level, crash)
}

tTestMtx <- function(x, f, type = "standard", alternative = "two.sided", conf_level = 0.95, crash = TRUE) {
    .Call('_fastTest_tTestMtx', PACKAGE = 'fastTest', x, f, type, alternative, conf_level, crash)
}

Split <- function(x, f) {
    .Call('_fastTest_Split', PACKAGE = 'fastTest', x, f)
}

SplitMtx <- function(x, f) {
    .Call('_fastTest_SplitMtx', PACKAGE = 'fastTest', x, f)
}

outerSum <- function(x, y, na_rm = TRUE) {
    .Call('_fastTest_outerSum', PACKAGE = 'fastTest', x, y, na_rm)
}

outerDelta <- function(x, y, na_rm = TRUE) {
    .Call('_fastTest_outerDelta', PACKAGE = 'fastTest', x, y, na_rm)
}

outerProduct <- function(x, y, na_rm = TRUE) {
    .Call('_fastTest_outerProduct', PACKAGE = 'fastTest', x, y, na_rm)
}

crossProduct <- function(x, y) {
    .Call('_fastTest_crossProduct', PACKAGE = 'fastTest', x, y)
}

testWilcoxonVec <- function(x, f, type = "standard", alternative = "two.sided", exact = FALSE, correct = TRUE, hl_estimate = FALSE, crash = TRUE) {
    .Call('_fastTest_testWilcoxonVec', PACKAGE = 'fastTest', x, f, type, alternative, exact, correct, hl_estimate, crash)
}

testWilcoxonStd <- function(x, y, type = "standard", alternative = "two.sided", exact = FALSE, correct = TRUE, hl_estimate = FALSE, crash = TRUE) {
    .Call('_fastTest_testWilcoxonStd', PACKAGE = 'fastTest', x, y, type, alternative, exact, correct, hl_estimate, crash)
}

testWilcoxonMtx <- function(x, f, type = "standard", alternative = "two.sided", exact = FALSE, correct = TRUE, hl_estimate = FALSE, crash = TRUE) {
    .Call('_fastTest_testWilcoxonMtx', PACKAGE = 'fastTest', x, f, type, alternative, exact, correct, hl_estimate, crash)
}

